server:
  port: 8080
  servlet:
    context-path: /api
spring:
  profiles:
    active: local
  application:
    name: eunomia-picture.backend
  # database config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eunomia_picture
    username: root
    password: 1234
  # Redis 配置
  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}
    timeout: ${redis.timeout}
#    password: ${redis.password}
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    # Mybatis config
    map-underscore-to-camel-case: false
    # Print log info only for develop environment
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # deleted
      logic-not-delete-value: 0 # not deleted
knife4j:
  enable: true
  openapi:
    title: api doc
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.zuning.eunomiapicturebackend.controller
# 对象存储服务配置
cos:
  client:
    host: ${cos.client.host}
    secretId: ${cos.client.secretId}
    secretKey: ${cos.client.secretKey}
    region: ${cos.client.region}
    bucket: ${cos.client.bucket}