server:
  port: 8080
  servlet:
    context-path: /api
    #cookie 30天过期
    session:
      cookie:
        max-age: 604800
spring:
  profiles:
    active: local
  application:
    name: eunomia-picture.backend
  # database config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eunomia_picture?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
  session:
    store-type: redis
    timeout: 604800
  # Redis 配置
  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}
    timeout: ${redis.timeout}
#    password: ${redis.password}
  servlet:
    multipart:
      max-file-size: 10MB


  # 空间图片分表
  shardingsphere:
    datasource:
      names: eunomia_picture
      eunomia_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/eunomia_picture?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 1234
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: eunomia_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.zuning.eunomiapicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true

mybatis-plus:
  configuration:
    # Mybatis config
    map-underscore-to-camel-case: false
    # Print log info only for develop environment
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # deleted
      logic-not-delete-value: 0 # not deleted
    enable-sql-runner: true
knife4j:
  enable: true
  openapi:
    title: api doc
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.zuning.eunomiapicturebackend.controller
# 对象存储服务配置
cos:
  client:
    host: ${cos.client.host}
    secretId: ${cos.client.secretId}
    secretKey: ${cos.client.secretKey}
    region: ${cos.client.region}
    bucket: ${cos.client.bucket}

# 阿里云AI配置
aliYunAi:
  apiKey: ${aliYunAi.apiKey}