server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: eunomia-picture.backend
  # database config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eunomia_picture
    username: root
    password: 1234
mybatis-plus:
  configuration:
    # Mybatis config
    map-underscore-to-camel-case: false
    # Print log info only for develop environment
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # deleted
      logic-not-delete-value: 0 # not deleted
knife4j:
  enable: true
  openapi:
    title: api doc
    version: 1.0
    group:
      default:
        group-name: default group
        api-rule: package
        api-rule-resources:
          - com.zuning.eunomiapicturebackend.controller
